ExameApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls.static import static #Não tem no manual
from django.conf import settings #Não tem no manual

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('pacientes/', include('patients.urls', namespace='patients')),
    path('especialidades/', include('specialities.urls', namespace='specialities')),
    path('doutores/', include('doctors.urls', namespace='doctors')),
    path('locais/', include('locales.urls', namespace='locales')),
    path('agendas/', include('schedules.urls', namespace='schedules')),
    path('exames/', include('exams.urls', namespace='exams')),
    path('AgendasExames/', include('schedules_exams.urls', namespace='schedules_exams')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'

urlpatterns = [
    path('', views.list_patients, name='list_patients'),
    path('adicionar/', views.add_patient, name='add_patient'),
    path('editar/<int:id_patient>/', views.edit_patient, name='edit_patient'),
    path('excluir/<int:id_patient>/', views.delete_patient, name='delete_patient'),
    path('buscar/', views.search_patients, name='search_patients'),
]

apps/schedules/urls.py
from django.urls import path
from . import views

app_name = 'schedules'

urlpatterns = [
    path('', views.list_schedules, name='list_schedules'),
    path('adicionar/<int:id_patient>/', views.add_scheduling, name='add_scheduling'),
    path('editar/<int:id_scheduling>/', views.edit_scheduling, name='edit_scheduling'),
    path('excluir/<int:id_scheduling>/', views.delete_scheduling, name='delete_scheduling'),
    path('editar-status/<int:id_scheduling>/', views.edit_scheduling_status, name='edit_scheduling_status'),
]

apps/patients/models.py
from apps import doctors
from django.db import models

# Create your models here.

class Patient(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    first_name = models.CharField('Nome', max_length=50)
    last_name = models.CharField('Sobrenome', max_length=100) 
    address = models.CharField('Endereco', max_length=200)   
    cell_phone = models.CharField('Telefone celular', max_length=20)
    email = models.EmailField('E-mail',null=False, blank=False)
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro'),
    )
    gender = models.CharField('Genero', max_length=1, choices=GENDER_CHOICES)
    photo = models.ImageField('Foto', upload_to='photos')
    
    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'
        ordering =['id']

    def __str__(self):
        return self.first_name

        

apps/patients/forms.py
from django import forms
from .models import Patient

class PatientForm(forms.ModelForm):

    class Meta:
        model = Patient
        exclude = ('created_on' , 'updated_on',)

apps/patients/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import PatientForm
from .models import Patient

# Create your views here.

@login_required(login_url='/contas/login/')
def add_patient(request):
    template_name = 'patients/add_patient.html'
    context = {}
    if request.method == 'POST':
        form = PatientForm(request.POST, request.FILES)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('patients:list_patients')
    form = PatientForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_patients(request):
    template_name = 'patients/list_patients.html'
    patients = Patient.objects.filter()
    context = {
        'patients': patients
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_patient(request, id_patient):
    template_name = 'patients/add_patient.html'
    context ={}
    patient = get_object_or_404(Patient, id=id_patient)
    if request.method == 'POST':
        form = PatientForm(request.POST, instance=patient)
        if form.is_valid():
            form.save()
            return redirect('patients:list_patients')
    form = PatientForm(instance=patient)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_patient(request, id_patient):
    patient = Patient.objects.get(id=id_patient)
    patient.delete()
    return redirect('patients:list_patients')

@login_required(login_url='/contas/login/')
def search_patients(request):
    template_name = 'patients/list_patients.html'
    query = request.GET.get('query')
    patients = Patient.objects.filter(last_name__icontains=query)
    context = {
        'patients': patients,
    }
    return render(request,template_name, context)    

templates/patients/add_patient.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Paciente - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro de Paciente</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.first_name.id_for_label }}">Nome</label>
                   {{ form.first_name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
                    {{ form.last_name|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">Endereco</label>
                    {{ form.address|add_class:"form-control" }}
                </div>
                <div class="form-group">
                  <label for="{{ form.cell_phone.id_for_label }}">Telefone</label>
                  {{ form.cell_phone|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">E-mail</label>
                    {{ form.email|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.gender.id_for_label }}">Genero</label>
                    {{ form.gender|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.photo.id_for_label }}">Foto</label>
                    {{ form.photo|add_class:"form-control-file" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/patients/list_patients.html
{% extends 'base.html' %}

{% block title %}

    Lista de Pacientes - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Pacientes</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                    <a href="{% url 'patients:add_patient' %}">Cadastro de novo paciente</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>   
                    <th scope="col">#</th>
                    <th scope="col">Foto</th> 
                    <th scope="col">Nome</th>
                    <th scope="col">Sobrenome</th>
                    <th scope="col">Endereco</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Genero</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for patient in patients %}
                        <tr>
                            <th scope="row">{{ patient.id }}</th>
                            <td>
                                <img src="{{ patient.photo.url }}" width="50" height="50">
                            </td>
                            <td>{{ patient.first_name }}</td>
                            <td>{{ patient.last_name }}</td>
                            <td>{{ patient.address }}</td>
                            <td>{{ patient.cell_phone }}</td>
                            <td>{{ patient.email }}</td>
                            <td>{{ patient.gender }}</td>

                            <td></td>
                            <td style='text-align:right;'>
                                <a href="{% url 'patients:edit_patient' patient.id %}" class="btn btn-primary btn-sm">Editar</a>
                            </td>
                            <td style='text-align:right;'>
                                <a href="{% url 'patients:delete_patient' patient.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                            <td style='text-align:right;'>
                                <a href="{% url 'schedules:add_scheduling' patient.id %}" class="btn btn-danger btn-sm ">Agendar</a>
                            </td>

                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}