ExameApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls.static import static #Não tem no manual
from django.conf import settings #Não tem no manual

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('pacientes/', include('patients.urls', namespace='patients')),
    path('especialidades/', include('specialities.urls', namespace='specialities')),
    path('doutores/', include('doctors.urls', namespace='doctors')),
    path('locais/', include('locales.urls', namespace='locales')),
    path('agendas/', include('schedules.urls', namespace='schedules')),
    path('exames/', include('exams.urls', namespace='exams')),
    path('AgendasExames/', include('schedules_exams.urls', namespace='schedules_exams')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/schedules/urls.py
from django.urls import path
from . import views

app_name = 'schedules'

urlpatterns = [
    path('', views.list_schedules, name='list_schedules'),
    path('adicionar/<int:id_patient>/', views.add_scheduling, name='add_scheduling'),
    path('editar/<int:id_scheduling>/', views.edit_scheduling, name='edit_scheduling'),
    path('excluir/<int:id_scheduling>/', views.delete_scheduling, name='delete_scheduling'),
    path('editar-status/<int:id_scheduling>/', views.edit_scheduling_status, name='edit_scheduling_status'),
]

apps/schedules_exams/urls.py
from django.urls import path
from . import views

app_name = 'schedules_exams'

urlpatterns = [
    path('adicionar/<int:id_scheduling>/', views.add_scheduling_exam, name='add_scheduling_exam'),
    path('excluir/<int:id_scheduling_exam>/', views.delete_scheduling_exam, name='delete_scheduling_exam'),
]

apps/schedules/models.py
from django.db import models
from patients.models import Patient
from locales.models import Locale
 
# Create your models here.

class Scheduling(models.Model):
    
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    date = models.DateField('Data', auto_now=False, auto_now_add=False)
    hour = models.CharField('Horario', max_length=5)
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    locale = models.ForeignKey(Locale, on_delete=models.CASCADE)
    
    STATUS_CHOICES = (
        ('Agendado', 'Agendado'),
        ('Finalizado', 'Finalizado'),
        ('Cancelado', 'Cancelado'),
    )
    status = models.CharField('Status', max_length=20, choices=STATUS_CHOICES, null=True, blank=True, default='Agendado')

    class Meta:
        verbose_name = 'Agenda'
        verbose_name_plural = 'Agendas'
        ordering =['-id']

    def _str_(self):
        return self.date

apps/schedules/forms.py
from django import forms
from .models import Scheduling, Patient

class SchedulingForm(forms.ModelForm):

    class Meta:
        model = Scheduling
        exclude = ('patient', 'created_on' , 'updated_on',)        

apps/schedules/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .forms import SchedulingForm
from .models import Scheduling, Patient, Locale 
from schedules_exams.models import SchedulingExam
from exams.models import Exam
from doctors.models import Doctor, Speciality, DoctorSpeciality
from apps import schedules


# Create your views here.

@login_required(login_url='/contas/login/')
def add_scheduling(request, id_patient):
    template_name = 'schedules/add_scheduling.html'
    context = {}
    if request.method == 'POST':
        form = SchedulingForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.patient = Patient.objects.get(id=id_patient)
            f.save()
            form.save_m2m()
            return redirect('schedules:list_schedules')
    form = SchedulingForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_schedules(request):
    template_name = 'schedules/list_schedules.html'
    patients = Patient.objects.filter()
    locales = Locale.objects.filter()
    schedules = Scheduling.objects.filter()
    schedules_exams = SchedulingExam.objects.filter()
    exams = Exam.objects.filter()
    doctors = Doctor.objects.filter()
    doctors_specialities = DoctorSpeciality.objects.filter()
    specialities = Speciality.objects.filter()
    context = {
        'patients': patients,
        'locales': locales,
        'schedules': schedules,
        'schedules_exams' : schedules_exams,
        'exams' : exams,
        'doctors' : doctors,
        'specialities': specialities,
        'doctors_specialities': doctors_specialities,
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_scheduling(request, id_scheduling):
    template_name = 'schedules/add_scheduling.html'
    context ={}
    scheduling = get_object_or_404(Scheduling, id=id_scheduling)
    if request.method == 'POST':
        form = SchedulingForm(request.POST, instance=scheduling)
        if form.is_valid():
            form.save()
            return redirect('schedules:list_schedules')
    form = SchedulingForm(instance=scheduling)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_scheduling(request, id_scheduling):
    scheduling = Scheduling.objects.get(id=id_scheduling)
    scheduling.delete()
    return redirect('schedules:list_schedules')

@login_required(login_url='/contas/login/')
def edit_scheduling_status(request, id_scheduling):
    template_name = 'schedules/edit_scheduling_status.html'
    context ={}
    scheduling = get_object_or_404(Scheduling, id=id_scheduling)
    if request.method == 'POST':
        form = SchedulingForm(request.POST, instance=scheduling)
        if form.is_valid():
            form.save()
            return redirect('Schedules:list_schedules')
    form = SchedulingForm(instance=scheduling)
    context['form'] = form
    return render(request, template_name, context)    

templates/schedules/add_scheduling.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Agendamento - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Agendamentos</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                   <label for="{{ form.date.id_for_label }}">Data</label>
                   {{ form.date|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.hour.id_for_label }}">Hora</label>
                    {{ form.hour|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.locale.id_for_label }}">Locais</label>
                    {{ form.locale|add_class:"form-control" }}
                </div>

                <div class="form-group">
                    <label for="{{ form.status.id_for_label }}">Status</label>
                    {{ form.status|add_class:"form-control" }}
                 </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/schedules/edit_scheduling_status.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Alterar status do Agendamento- {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Alterar Status do Agendamento</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                       <label for="{{ form.status.id_for_label }}">Data</label>
                       {{ form.status|add_class:"form-control" }}
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/schedules/list_schedules.html
{% extends 'base.html' %}

{% block title %}

    Lista de Agendamentos - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Agendamentos</b></h5>
        <div class="row">
            <div class ="col-md-12">
            <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Status</th>
                    <th scope="col">Paciente</th>
                    <th scope="col">Local</th>
                    <th scope="col">Data</th>
                    <th scope="col">Hora</th>
                    <th scope="col">Exames</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for scheduling in schedules %}
                        <tr>
                            <th scope="row">
                                {% if scheduling.status == 'Finalizado' or scheduling.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >{{ scheduling.id }}</p>
                                {% else %}
                                    {{ scheduling.id }}
                                {% endif %}
                            </th>

                            <td>
                                {% if scheduling.status == 'Finalizado' or scheduling.status == 'Cancelado' %}
                                    <p style="color:darkgray;" >{{ scheduling.status }}</p>
                                {% else %}
                                    {{ scheduling.status }}
                                {% endif %}
                                
                            </td>
                            <td>
                                {% for patient in patients %}
                                    {% for locale in locales %}
                                        {% if scheduling.patient_id == patient.id and scheduling.locale_id == locale.id%}
                                            {% if scheduling.status == 'Finalizado' or scheduling.status == 'Cancelado' %}
                                                <p style="color:darkgray;" >{{ patient.first_name }} {{ patient.last_name }}</p>
                                                <td><p style="color:darkgray;" >{{ locale.address }}</p></td>
                                                <td><p style="color:darkgray;" >{{ scheduling.date }}</p></td>
                                                <td><p style="color:darkgray;" >{{ scheduling.hour }}</p></td>
                                            {% else %}    
                                                {{ patient.first_name }} {{ patient.last_name }}
                                                <td>{{ locale.address }}</td>
                                                <td>{{ scheduling.date }}</td>
                                                <td>{{ scheduling.hour }}</td>
                                            {% endif %}    
                                        {% endif %}      
                                    {% endfor %}     
                                {% endfor %}
                            </td>
                            <td>
                                {% if scheduling.status == 'Finalizado' or scheduling.status == 'Cancelado' %}
                                    <b style="color:darkgray;">Preço Total:</b>
                                    {% for scheduling_exam in schedules_exams %}
                                        {% if  scheduling_exam.scheduling_id == scheduling.id %}
                                        </br></br><b style="color:darkgray;">Exame: {{ scheduling_exam.exam}}</b>
                                            {% for exam in exams %}
                                                {% if scheduling_exam.exam_id == exam.id %}
                                                    </br><p1 style="color:darkgray;"><b>Preço:</b> {{ exam.price }}</p1>
                                                {% endif %}
                                            {% endfor %}     
                                            </br><p1 style="color:darkgray;"><b>Doutor:</b> {{ scheduling_exam.doctor}}</p1>
                                                {% for doctor_speciality in doctors_specialities %}
                                                    {% if doctor_speciality.doctor_id == scheduling_exam.doctor_id %}
                                                        {% for speciality in specialities %}
                                                            {% if doctor_speciality.speciality_id == speciality.id %}
                                                                <br><p1 style="color:darkgray;"><b>Especialidade:</b> {{ speciality.name }}</p1>
                                                            {% endif %}
                                                        {% endfor %}    
                                                    {% endif %}
                                                {% endfor %}
                                                <a style="color:darkgray;" href="#">Excluir Exame</a>
                                        {% endif %} 
                                    {% endfor %}
                                {% else %}
                                    <b>Preço Total:</b> 
                                    {% for scheduling_exam in schedules_exams %}
                                        {% if  scheduling_exam.scheduling_id == scheduling.id %}
                                        </br></br><b>Exame: {{ scheduling_exam.exam}}</b>
                                            {% for exam in exams %}
                                                {% if scheduling_exam.exam_id == exam.id %}
                                                    </br><b>Preço:</b> {{ exam.price }}
                                                {% endif %}
                                            {% endfor %}     
                                            </br><b>Doutor:</b> {{ scheduling_exam.doctor}}
                                                {% for doctor_speciality in doctors_specialities %}
                                                    {% if doctor_speciality.doctor_id == scheduling_exam.doctor_id %}
                                                        {% for speciality in specialities %}
                                                            {% if doctor_speciality.speciality_id == speciality.id %}
                                                                <br><b>Especialidade:</b> {{ speciality.name }}
                                                            {% endif %}
                                                        {% endfor %}    
                                                    {% endif %}
                                                {% endfor %}
                                                <a href="{% url 'schedules_exams:delete_scheduling_exam' scheduling_exam.id %}">Excluir Exame</a>
                                        {% endif %} 
                                    {% endfor %}
                                {%endif%}

                                
                            </td>
                            {% if scheduling.status == 'Finalizado' or scheduling.status == 'Cancelado' %}
                                <td><a href="#" class="btn btn-primary btn-sm">Exames</a></td>
                            {% else %}
                                <td><a href="{% url 'schedules_exams:add_scheduling_exam' scheduling.id %}" class="btn btn-primary btn-sm">Exames</a></td>
                            {% endif %}    
                            <td><a href="{% url 'schedules:edit_scheduling' scheduling.id %}" class="btn btn-primary btn-sm">Editar</a></td>
                            <td><a href="{% url 'schedules:delete_scheduling' scheduling.id %}" class="btn btn-danger btn-sm ">Excluir</a></td>    
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}