ExameApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls.static import static #Não tem no manual
from django.conf import settings #Não tem no manual

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('pacientes/', include('patients.urls', namespace='patients')),
    path('especialidades/', include('specialities.urls', namespace='specialities')),
    path('doutores/', include('doctors.urls', namespace='doctors')),
    path('locais/', include('locales.urls', namespace='locales')),
    path('agendas/', include('schedules.urls', namespace='schedules')),
    path('exames/', include('exams.urls', namespace='exams')),
    path('AgendasExames/', include('schedules_exams.urls', namespace='schedules_exams')),
    path('contas/', include('accounts.urls', namespace='accounts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/locales/urls.py
from django.urls import path
from . import views

app_name = 'locales'

urlpatterns = [
    path('', views.list_locales, name='list_locales'),
    path('adicionar/', views.add_locale, name='add_locale'),
    path('editar/<int:id_locale>/', views.edit_locale, name='edit_locale'),
    path('excluir/<int:id_locale>/', views.delete_locale, name='delete_locale'),
]

apps/locales/models.py
from django.db import models

# Create your models here.

class Locale(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    address = models.CharField('Endereco', max_length=200)   
    cell_phone = models.CharField('Telefone celular', max_length=20)
    
    class Meta:
        verbose_name = 'Local'
        verbose_name_plural = 'Locais'
        ordering =['id']

    def __str__(self):
        return self.address

apps/locales/forms.py
from django import forms
from .models import Locale

class LocaleForm(forms.ModelForm):

    class Meta:
        model = Locale
        exclude = ('created_on' , 'updated_on',)

apps/locales/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import LocaleForm
from .models import Locale

# Create your views here.

@login_required(login_url='/contas/login/')
def add_locale(request):
    template_name = 'locales/add_locale.html'
    context = {}
    if request.method == 'POST':
        form = LocaleForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.save()
            form.save_m2m()
            return redirect('locales:list_locales')
    form = LocaleForm()
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def list_locales(request):
    template_name = 'locales/list_locales.html'
    locales = Locale.objects.filter()
    context = {
        'locales': locales
    }
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def edit_locale(request, id_locale):
    template_name = 'locales/add_locale.html'
    context ={}
    locale = get_object_or_404(Locale, id=id_locale)
    if request.method == 'POST':
        form = LocaleForm(request.POST, instance=locale)
        if form.is_valid():
            form.save()
            return redirect('locales:list_locales')
    form = LocaleForm(instance=locale)
    context['form'] = form
    return render(request, template_name, context)

@login_required(login_url='/contas/login/')
def delete_locale(request, id_locale):
    locale = Locale.objects.get(id=id_locale)
    locale.delete()
    return redirect('locales:list_locales')

templates/locales/add_locale.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Locais - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
    <h5><b>Cadastro da Filial</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <form action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.address.id_for_label }}">Endereco</label>
                    {{ form.address|add_class:"form-control" }}
                </div>
                <div class="form-group">
                  <label for="{{ form.cell_phone.id_for_label }}">Telefone</label>
                  {{ form.cell_phone|add_class:"form-control" }}
                </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>       
                </form>
            </div>
        </div>
    </div>

{% endblock body %}

templates/locales/list_locales.html
{% extends 'base.html' %}

{% block title %}

    Lista de Filiais - {{ block.super }}

{% endblock title %}

{% block body %}

    <div class="container">
        <br />
        <h5><b>Lista de Filiais</b></h5>
        <div class="row">
            <div class ="col-md-12">
                <br />
                <a href="{% url 'locales:add_locale' %}">Cadastro de novo endereço</a>
                <br />
                <br />
                <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Endereco</th>
                    <th scope="col">Telefone</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for locale in locales %}
                        <tr>
                            <th scope="row">{{ locale.id }}</th>
                            <td>{{ locale.address }}</td>
                            <td>{{ locale.cell_phone }}</td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td style='text-align:right;'>
                                <a href="{% url 'locales:edit_locale' locale.id %}" class="btn btn-primary btn-sm">Editar</a>
                                <a href="{% url 'locales:delete_locale' locale.id %}" class="btn btn-danger btn-sm ">Excluir</a>
                            </td>
                        </tr> 
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock body %}